# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
inhibit_all_warnings!

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end

target 'Section2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Player

  pod 'SnapKit', '5.6.0'
  pod 'Alamofire', '5.8.1'
  pod 'AlamofireImage', '4.3.0'
  pod 'ObjectMapper', '4.2.0'
  pod 'IQKeyboardManagerSwift', '6.5.6'

end
